#version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
    image: django_dz
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./mysite/database:/app/database
      - ./mysite/static:/app/static
      - ./mysite/media:/app/media
      - ./mysite/logs:/app/logs


  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./mysite/static:/app/static
      - ./mysite/media:/app/media

    depends_on:
      - app