# Generated by Django 5.1.5 on 2025-01-30 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recept', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('ingredients', models.TextField(help_text='После каждого ингредиента ставьте ";" для разделения')),
                ('cooking_steps', models.TextField(help_text='После каждого шага ставьте ";" для разделения')),
                ('cooking_time', models.TimeField(help_text='Формат "чч:мм"')),
                ('image', models.ImageField(upload_to='recipe_website')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='recipe_website.categories')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe_website.recipes')),
            ],
        ),
    ]
